name: Build and Test (Feature)

on:
  push:
    branches:
      - feature/*

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Pull and Checkout code
          run: echo "Pulling and checking out from the git repository"

        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt' # or 'zulu'
            java-version: '11'

        - name: Build with Maven
          run: mvn clean install

        - name: Run Unit Tests
          run: mvn test
